Fix Sequence isinstance check on python3.10
Importing Sequence directly from collections was deprecated in
python3.10.

Fixes:
AttributeError: module 'collections' has no attribute 'Sequence'

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>