buffer.c: add missing include <stdlib.h>
Without:

$ make CFLAGS="-Wall"
...
  CC       buffer.o
buffer.c: In function ‘buffer_init’:
buffer.c:144:13: warning: implicit declaration of function ‘malloc’ [-Wimplicit-function-declaration]
  buf->buf = malloc(datasize);
             ^
buffer.c:144:13: warning: incompatible implicit declaration of built-in function ‘malloc’
buffer.c:144:13: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’

Signed-off-by: Michael Heimpold <mhei@heimpold.de>
Signed-off-by: Corey Minyard <cminyard@mvista.com>