configure.ac: fix USE_PTHREADS define
Without this change headers within a USE_PTHREADS ifdef statement are
still included.

Fixes:
ser2net.c:51:10: fatal error: pthread.h: No such file or directory
 #include <pthread.h>
          ^~~~~~~~~~~
compilation terminated.

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
[There were a couple of #if USE_PTHREADS that needed to be changed to
 #ifdef, with that I think this is correct.]
Signed-off-by: Corey Minyard <cminyard@mvista.com>